-- 0011_backfill_admin_email_verified.sql
-- แก้ผลกระทบจาก migration 0009 (add_email_verification) บน environment ที่
-- เพิ่งติดตั้งฐานข้อมูลแบบ "fresh install" (import schema.sql สดๆ แล้วรัน
-- seed.sql แล้วค่อย `npm run migrate:baseline`) — baseline แค่บันทึกว่า
-- migration ก่อนหน้าถูก "ติดตั้งแล้ว" โดยไม่ได้รัน SQL จริงของ 0009 (เพราะ
-- schema.sql มีคอลัมน์ email_verified อยู่แล้วตั้งแต่ต้น) แปลว่า UPDATE
-- backfill ของ 0009 ไม่เคยรันจริงบน environment แบบนี้เลย
--
-- ผลคือทุกบัญชีที่มีอยู่ก่อนอัปเดตนี้ (ทั้ง admin จาก seed.sql และผู้เช่าที่
-- สมัครไว้ก่อนหน้าบน production จริง) ค้างอยู่ที่ email_verified=0 →
-- login ไม่ได้เลยทั้งระบบตั้งแต่ deploy ฟีเจอร์นี้ครั้งแรก ทั้งที่ตั้งใจ
-- ให้เฉพาะบัญชีที่สมัคร/เปลี่ยนอีเมล "หลัง" อัปเดตนี้เท่านั้นที่ต้องยืนยัน
--
-- ทำ backfill เดียวกับ 0009 ทุกประการ (แค่รันซ้ำให้ชัวร์ เผื่อ 0009 โดน
-- baseline ข้ามไปจริงบาง environment) — ไม่จำกัดแค่ role='admin' เพราะ
-- ต้องการให้ "บัญชีที่มีอยู่แล้วก่อนอัปเดต" ทุกบัญชีไม่ต้องยืนยันซ้ำ
--
-- Idempotent: WHERE email_verified = 0 เท่านั้น รันซ้ำได้ปลอดภัย และรัน
-- แค่ครั้งเดียวตอน deploy รอบที่มีไฟล์นี้ — บัญชีที่สมัคร/เปลี่ยนอีเมลใหม่
-- "หลัง" จุดนี้ไปแล้วจะยังต้องยืนยันตามปกติ ไม่ได้รับการยกเว้นตามมา

UPDATE `users` SET `email_verified` = 1 WHERE `email_verified` = 0;
